/* tomo-usage.js — practical 'How to use it' notes per week/day (rendered as a callout). Mutates window.TOMO_USAGE so load order doesn't matter. */
(function () { var G = (window.TOMO_USAGE = window.TOMO_USAGE || {});
G[1] = [
'Reach for this the moment you want to <b>link a verb to anything else</b> — a request, an “-ing,” a “please.” With る-verbs it’s effortless: drop <b>る</b> and add <b>て</b>, so 食べる→<b>食べて</b>, 見る→<b>見て</b>. Remember it’s never a full sentence on its own — the て-form is the hook the next piece hangs on, so drill it until 見て pops out without thinking.',
'When your u-verb ends in <b>う, つ, or る</b>, snap that last kana off and add <b>って</b>: 買う→<b>買って</b>, 待つ→<b>待って</b>, 帰る→<b>帰って</b>. The little っ is a tiny catch in the throat — say “ka-t-te,” not “kate.” Watch out for sneaky 帰る: it <i>looks</i> like a る-verb but behaves as an u-verb, so it’s 帰って, never 帰て.',
'For u-verbs ending in <b>む, ぶ, or ぬ</b>, the ending becomes <b>んで</b> — note the voiced <b>で</b>, not て. So 飲む→<b>飲んで</b>, 遊ぶ→<b>遊んで</b>, 死ぬ→<b>死んで</b>. Let the <b>ん</b> hum before the で. Handy fact: 死ぬ is the <i>only</i> everyday ぬ-verb, so once you’ve got these three sounds, the whole group is yours.',
'Verb ends in <b>く</b>? It becomes <b>いて</b>: 書く→<b>書いて</b>. Ends in <b>ぐ</b>? Voiced <b>いで</b>: 泳ぐ→<b>泳いで</b>. The one troublemaker to memorize now is <b>行く</b> — despite the く it goes <b>行って</b>, never 行いて. Say “itte” for “go” and you’ll sound right every time you give directions or talk about heading somewhere.',
'Last piece: verbs ending in <b>す</b> take <b>して</b> — 話す→<b>話して</b>, 貸す→<b>貸して</b>. Then just memorize the two irregulars: <b>する→して</b> and <b>来る→来て（きて）</b>. This is quietly the most useful rule, because every 〜する word rides along: 勉強する→<b>勉強して</b>, 電話する→<b>電話して</b>. Nail these and you can て-form basically any verb you meet.',
'This is your go-to for telling someone about your day or a plan as a <b>sequence</b>: do this, <i>then</i> that. Chain with the て-form and let only the <b>final</b> verb carry the tense: 起きて、コーヒーを飲んで、<b>出かけました</b> — “I got up, had coffee, and headed out.” Don’t mark past on the middle verbs; the last one covers everyone, keeping the whole story tidy.',
'Use this when you want the て-form to come <b>automatically</b>, mid-conversation, with no pause. The drill: spot the group, fire the ending — る→て; う・つ・る→って; む・ぶ・ぬ→んで; く→いて, ぐ→いで; す→して; plus 行って, して, 来て. Say them out loud as a little chant until they’re reflex, and the whole grammar year opens up from here.'
];
G[2] = [
'Everything this week — requests, “-ing,” states — bolts onto the て-form, so make it your warm-up reflex. Run one verb from each group before you speak: 見る→<b>見て</b>, 買う→<b>買って</b>, 飲む→<b>飲んで</b>, 書く→<b>書いて</b>, 話す→<b>話して</b>, plus <b>して・来て・行って</b>. Once the ending fires without thinking, the polite “please” and the “-ing” forms are just one syllable away.',
'When you need someone to <i>do</i> something — pass the salt, wait a sec, look here — reach for <b>て-form + ください</b>: 待つ→<b>待ってください</b>, 見る→<b>見てください</b>. It’s polite, but it’s still a request, so cushion it with <b>すみません、</b> or <b>ちょっと</b> when asking a favor. Among friends, just drop ください: <b>待って！</b> on its own means “hang on!”',
'Reach for this to say what’s going on <b>right now</b> — perfect for answering 今何をしていますか (“what are you doing?”). Build it with <b>て-form + います</b>: 食べる→<b>食べています</b>, 待つ→<b>待っています</b>. In casual speech the い quietly drops to <b>〜てる</b>: <b>今、テレビ見てる</b> — “I’m watching TV right now.” Same meaning, comfier register.',
'Same <b>て-form + います</b>, but here it marks a <b>state that still holds</b> after the action — not an action in motion. 結婚する→<b>結婚しています</b> means “I’m married” (not “marrying right now”); 住む→<b>住んでいます</b> is where you live. The classic trap: “I know” is <b>知っています</b>, never 知ります. Translate these with English present tense, not “-ing.”',
'Use this contrast to say whether you’re doing something <i>at this moment</i> or <i>as a rule</i>. <b>今、食べています</b> = eating right now; <b>毎日食べます</b> = I eat every day. Pair time words to keep it clear: <b>今・今日</b> lean toward ています, while <b>毎日・いつも</b> point to plain ます. Mix them up and you’ll accidentally say you eat around the clock.',
'Three everyday moves here. To say something <i>isn’t</i> happening, use <b>〜ていません</b> — often with まだ: <b>まだ食べていません</b>, “I haven’t eaten yet.” Casually, that’s <b>食べてない</b>. And to ask someone <i>not</i> to do something, it’s <b>ない-form + でください</b>: <b>心配しないでください</b>, “please don’t worry.” Match the casual endings to friends, the full ones to strangers.',
'Bring the week together by letting one て-form branch three ways: add <b>ください</b> to request, <b>います</b> to say “-ing” or a state, <b>ないでください</b> to ask someone to stop. Try a mini exchange: <b>すみません、ちょっと待ってください。今、電話しています。</b> — “Sorry, please wait a moment; I’m on the phone right now.” Pick the branch that matches what you actually need.'
];
G[3] = [
'When you want to check that something’s <b>allowed</b> — sitting here, opening a window, taking a photo — ask with <b>て-form + もいいですか</b>: 座る→<b>座ってもいいですか</b>, 撮る→<b>写真を撮ってもいいですか</b>. It’s the go-to polite way to test the waters before you act. With friends, shrink it to <b>〜てもいい？</b> with a rising tone: <b>これ食べてもいい？</b>',
'This is your reply when <i>you’re</i> the one giving the green light. Answer with <b>て-form + もいいです</b>: <b>食べてもいいですよ</b>, “sure, you can eat it.” That little <b>よ</b> makes it sound warm and generous rather than grudging. Casually it’s just <b>いいよ</b>, or skip the grammar entirely and offer a friendly <b>どうぞ</b> — “go ahead.”',
'Use this to lay down a firm <b>no</b> — the tone of signs, teachers, and parents. Build it with <b>て-form + はいけません</b>: <b>ここに入ってはいけません</b>, “you must not enter here.” It’s strong and top-down, so save it for real rules rather than personal preferences. Among friends the everyday version is <b>〜ちゃだめ</b>: <b>食べちゃだめ！</b> — “don’t eat that!”',
'Telling someone <i>not</i> to do something is all about picking the right strength for your listener. Softest and kindest is <b>ない-form + でください</b>: <b>ここで写真を撮らないでください</b>, “please don’t take photos here.” Drop ください for a friend: <b>撮らないで</b>. Save the blunt <b>〜てはいけません</b> or <b>〜ちゃだめ</b> for firm rules or close pals — the register matters as much as the words.',
'This is the reassuring one — “you don’t have to.” Take the ない-form, swap い for <b>くてもいいです</b>: 来る→<b>来なくてもいいです</b>, “you don’t need to come.” Reach for it to lift a burden: <b>今日は予約しなくてもいいですよ</b>, “no need to book today.” Casually it trims to <b>〜なくてもいい</b>: <b>急がなくてもいいよ</b> — “no rush.”',
'Now put it to work on real signs and house rules. Public notices love the compact <b>〜禁止</b>: <b>撮影禁止</b> = no photography, <b>立入禁止</b> = no entry — mentally unpack them as <b>〜てはいけません</b>. When you relay a rule to someone politely, soften it to a request: <b>ここでタバコを吸わないでください</b>, “please don’t smoke here.” Read the strong form, speak the gentle one.',
'Tie the week together with four moves off the same て-form. Ask: <b>座ってもいいですか</b>. Grant: <b>いいですよ</b>. Forbid: <b>入ってはいけません</b>. And excuse from duty: <b>来なくてもいいです</b>. Picture a scene — a museum, an office — and run all four in order. Choosing the right one for the moment is the real skill; the endings are just the toolkit.'
];
G[4] = [
'The dictionary form is more than a lookup entry — it’s already casual speech for “do” or “will do.” Among friends, <b>食べる</b> alone means “I’ll eat,” where politely you’d say 食べます. Sorting verbs into the three groups — <b>る-verbs</b>, <b>う-verbs</b>, and the two irregulars する・来る — is the map every other plain form is built from, so nail the grouping first.',
'Plain form shows up in two places. Socially, it’s the register for <b>friends, family, and people close to you</b> — drop the ます and just say <b>行く</b>. Grammatically, it’s <i>required</i> mid-sentence before things like と思う and から, even when you’re polite overall: <b>明日は雨が降ると思います</b> uses plain <b>降る</b> inside a polite sentence. Casual outside, plain inside.',
'This is the casual <b>〜ません</b> — “don’t” or “won’t” among friends. For る-verbs, drop る and add <b>ない</b>: 食べる→<b>食べない</b>. For う-verbs, shift the last sound to the <b>あ</b>-row then add ない: 行く→<b>行かない</b>, 飲む→<b>飲まない</b>. Irregulars are <b>しない</b> and <b>来ない（こない）</b>. One quirk worth memorizing: ある becomes plain <b>ない</b>, not あらない.',
'Describing things casually is mostly about <i>subtraction</i>. い-adjectives just drop the です: <b>これ、おいしい！</b> stands on its own. Nouns and な-adjectives take <b>だ</b> in place of です: <b>元気だ</b>, <b>学生だ</b> — though in relaxed, softer speech people often drop even the だ and just say <b>元気？</b>. Past tense follows suit: <b>高い→高かった</b>, <b>好きだ→好きだった</b>.',
'Casual questions ditch the か entirely — you just lift your <b>intonation</b> at the end. <b>もう食べた？</b>, <b>これ、好き？</b>. Careful with nouns and な-adjectives: drop the だ in questions, so it’s <b>学生？</b>, not 学生だ？. For a softer, more curious tone, tack on <b>〜の？</b>: <b>どこ行くの？</b> — “where are you off to?” It sounds warm and interested rather than blunt.',
'The forms are easy; the judgment is the real lesson. Default to polite <b>〜ます・です</b> with strangers, teachers, bosses, older people, and anyone at work — going plain too soon can land as rude or overfamiliar. Let the <b>senior person set the tone</b>; if they loosen up, you can follow. When unsure, stay polite — nobody’s ever offended by an extra ます.',
'The skill to lock in is <b>flipping a sentence either direction</b> on demand. Practice with one line: <b>明日、映画を見ます</b> ⇄ <b>明日、映画を見る</b>; <b>行きません</b> ⇄ <b>行かない</b>; <b>学生です</b> ⇄ <b>学生だ</b>. Say it politely for a colleague, then plainly for a friend. Sliding between registers on the fly is what makes you sound genuinely comfortable in Japanese.'
];
G[5] = [
'Here’s a gift: if you know the て-form, you already know the plain past. Just swap the ending — <b>て→た</b>, <b>で→だ</b> — and you’ve got casual “did.” 食べて→<b>食べた</b>, 飲んで→<b>飲んだ</b>, 行って→<b>行った</b>. It’s the friendly version of 〜ました: <b>昨日、映画を見た</b>, “I watched a movie yesterday.” No new rules to learn — the て-map does all the work.',
'For u-verbs ending <b>う, つ, る</b>, the past ending is <b>った</b> — exactly mirroring the って you already learned. 買う→<b>買った</b>, 待つ→<b>待った</b>, 帰る→<b>帰った</b>. Keep that little <b>っ</b> catch: “ka-t-ta.” And 帰る stays sneaky — it’s an u-verb, so <b>帰った</b>, “I went home,” not 帰た. If you can say 買って, you can already say 買った.',
'Same map as the て-form, just past-tense. む・ぶ・ぬ → <b>んだ</b>: 飲む→<b>飲んだ</b>. く → <b>いた</b>: 書く→<b>書いた</b>. ぐ → voiced <b>いだ</b>: 泳ぐ→<b>泳いだ</b>. And the rebel 行く is <b>行った</b> once again, never 行いた. Notice the voiced endings (んだ, いだ) echo the voiced て-forms — learn one, get the other for free.',
'Verbs ending <b>す</b> go to <b>した</b>: 話す→<b>話した</b>, and every 〜する word rides along — 勉強する→<b>勉強した</b>. The irregulars are <b>した</b> and <b>来た（きた）</b>. For the <i>polite</i> past, forget conjugation gymnastics: just turn ます into <b>ました</b> — <b>食べました</b>, <b>行きました</b>. Plain past for friends, 〜ました for everyone else.',
'To say “didn’t” casually, take the plain negative <b>〜ない</b> and treat its ない like an い-adjective: swap <b>い→かった</b>. So 食べない→<b>食べなかった</b>, 行かない→<b>行かなかった</b>. <b>昨日、宿題をしなかった</b> = “I didn’t do my homework yesterday.” The polite equivalent is <b>〜ませんでした</b>, so pick <b>しなかった</b> for friends, <b>しませんでした</b> for teachers.',
'This is the “have you ever…?” form — for <b>experiences</b>, not just something that happened once. Build it with <b>plain past + ことがある</b>: 食べる→<b>食べたことがあります</b>, “I’ve eaten it before.” Ask about someone’s life with <b>〜たことがありますか</b>: <b>日本に行ったことがありますか</b>, “have you ever been to Japan?” Note it’s the <i>plain</i> past + こと, even when the tail stays polite.',
'Pull it together: the plain past is your て-form with <b>て→た, で→だ</b>, so 書いて→<b>書いた</b>, 遊んで→<b>遊んだ</b> come out instantly. Add the two extensions — <b>〜なかった</b> for “didn’t” and <b>〜たことがある</b> for “have done.” Try a natural line: <b>京都に行ったことがあるけど、金閣寺は見なかった</b> — “I’ve been to Kyoto, but I didn’t see Kinkaku-ji.”'
];
G[6] = [
'This is your everyday “because.” State the <b>reason first</b>, cap it with <b>から</b>, then the result: <b>高いから、買いません</b>, “it’s expensive, so I won’t buy it.” It attaches to either plain or polite forms — <b>疲れたから帰る</b> works casually too. から carries a slightly <i>personal, subjective</i> feel, which makes it perfect for your own opinions and decisions.',
'When you want your reason to sound <b>softer and less pushy</b> — especially explaining yourself to a boss or making a polite excuse — reach for <b>ので</b> instead of から. It clips onto the plain form: <b>電車が遅れたので、遅れました</b>, “I was late because the train was delayed.” One catch: nouns and な-adjectives need <b>な</b> first — <b>病気なので</b>, not 病気だので. Gentler, more objective, very polite.',
'Use <b>んです</b> when you’re explaining the <i>backstory</i> — signaling “here’s what’s going on.” Say you decline an invite: a flat <b>行きません</b> feels curt, but <b>ちょっと用事があるんです</b>, “the thing is, I’ve got an errand,” sounds natural and warm. Attach んです to the plain form; nouns and な-adjectives take <b>な</b>: <b>学生なんです</b>. Casually it softens to just <b>〜の</b>: <b>疲れたの</b>.',
'Add <b>んですか</b> to a question when you want to sound <b>engaged and curious</b> rather than just gathering facts. Someone looks down, so you ask <b>どうしたんですか</b>, “what’s the matter?” — far warmer than a bare どうしましたか. It invites the <i>story</i> behind things: <b>日本語を勉強しているんですか</b>, “oh, are you studying Japanese?” Great for showing genuine interest and keeping a conversation going.',
'The て-form can carry a <b>light, feeling-based “because”</b> — gentler than から and everywhere in set phrases. Lead with the cause in て-form, then the emotion: <b>遅れてすみません</b>, “sorry for being late”; <b>会えて嬉しいです</b>, “I’m glad I could meet you”; <b>手伝ってくれてありがとう</b>, “thanks for helping.” It’s not for heavy logic — just the soft cause behind an apology, a thank-you, or a feeling.',
'Three “becauses,” three flavors. <b>から</b> is direct and personal — great for your opinions: <b>安いから好き</b>. <b>ので</b> is softer and more objective — the safe choice for excuses to a superior: <b>用事があるので、失礼します</b>. <b>んです</b> sets an explanatory tone, adding context rather than a bare fact. Rough rule: assert with から, apologize with ので, explain with んです — and lean polite when unsure.',
'Bring the toolkit together in a real moment — say you’re running late. String it naturally: <b>すみません、電車が遅れたので、少し遅れます。今、駅にいるんです。</b> — “Sorry, the train was delayed so I’ll be a bit late; I’m at the station right now.” Notice ので for the polite reason and んです for the background. Choosing the right “because” for the situation is the whole skill this week.'
];
G[7]=[
'Reach for this the moment you want to voice a craving or plan — food, a trip, a nap. Build it by taking the polite ます-stem and clicking on <b>たい</b>: 食べ<s>ます</s>→<b>食べたい</b>. It’s personal and a little emotional, so keep plain 〜たい for yourself or for questions; add です to be polite — <i>コーヒーが飲みたいです</i> (I’d like a coffee).',
'Once you can say “want to,” this lets you say you <i>didn’t</i>, or don’t anymore. Chop the い and treat たい like any い-adjective: 行き<b>たくない</b> (don’t want to go), 行き<b>たかった</b> (wanted to), 行き<b>たくなかった</b> (didn’t want to). Perfect for excuses — <i>昨日は何もしたくなかった</i> (I didn’t want to do anything yesterday).',
'Switch to this when you want a <i>thing</i> rather than an action — たい handles verbs, ほしい handles nouns. The formula is dead simple: noun + が + <b>ほしい</b>, as in <i>新しい靴がほしい</i> (I want new shoes). It flexes like an い-adjective too (ほしくない, ほしかった), and like たい it stays for your own wants or for questions.',
'This is the particle you second-guess mid-sentence. Both work: <i>寿司が食べたい</i> and <i>寿司を食べたい</i> are fine — が spotlights the craving itself, を just marks a plain object. Lean on が for short, heartfelt wants; を feels natural when other words sit between the object and the verb. Unsure in speech? Either one passes.',
'Use this when you report what <i>someone else</i> wants — Japanese avoids stating others’ feelings as flat fact. Convert たい to <b>たがっている</b> (彼は帰り<b>たがっている</b>, he wants to go home) for “shows signs of wanting,” or hedge with 〜たいようです / 〜たいと言っていた (said they want to). For your own wants, plain たい is still fine.',
'Reach for this when a blunt たい would sound childish and you need a grown-up ask. Wrap the want in <b>〜たいんですが…</b> and let it trail off: <i>予約したいんですが…</i> (I’d like to book, if that’s okay…). The unfinished ending invites help, and 〜んですが softens everything — your go-to move at counters, clinics, and front desks.',
'A quick decision map for the week: action you want → <b>たい</b> (見たい); thing you want → <b>がほしい</b> (水がほしい); someone else’s want → <b>たがっている</b>. All three flex like い-adjectives, so past and negative come free (たくなかった, ほしくない). In real talk, soften with 〜んですが whenever you’re actually asking a person for something.'
];
G[8]=[
'Your everyday “X is more … than Y.” Slot it as <b>AよりBのほうが</b> + adjective: <i>電車より車のほうが速い</i> (a car is faster than a train). より tags the one you’re beating (“than A”), のほうが tags the winner. You can drop either half when it’s obvious — <i>車のほうが速い</i> alone still clearly means “the car’s faster.”',
'The question that sets up a comparison: <b>AとBと、どちらが</b> + adjective + ですか — <i>コーヒーと紅茶と、どちらが好きですか</i> (which do you prefer, coffee or tea?). Always どちら for a two-way choice (casual <b>どっち</b>), never どれ. The reply loops back with のほうが: <i>コーヒーのほうが好きです</i>. Ideal for menus and getting someone off the fence.',
'For “the most / the -est,” just park <b>一番</b> in front of the adjective — 一番<b>安い</b> (cheapest), 一番<b>好き</b> (like best). Mark the group it wins within with で or の中で: <i>クラスで一番背が高い</i> (tallest in the class), <i>この中でどれが一番いい？</i> (which of these is best?). No special adjective ending needed — 一番 does the work.',
'Two comparisons that aren’t “more”: for equal, use <b>AはBと同じ</b> (<i>私のと同じ</i>, same as mine); for falling short, <b>AはBほど〜ない</b> — <i>今日は昨日ほど暑くない</i> (today isn’t as hot as yesterday). Note that ほど always pairs with a negative, and it quietly implies B is still the bigger one. Great for soft, indirect “it’s a bit less…” remarks.',
'These adverbs fine-tune the dial. <b>もっと</b> = more (<i>もっと欲しい</i>), <b>ずっと</b> = way more, by far (<i>ずっと安い</i>, far cheaper — not “always” here), <b>もう少し</b> = a bit more. Drop them straight in front of the word they boost. Super useful when haggling or asking a favour: <i>もう少し安くなりませんか</i> (could you go a little cheaper?).',
'This is the week’s toolkit at the shop counter. Compare two — <i>こっちのほうが大きいけど、高い</i> (this one’s bigger but pricier) — or crown a winner with 一番: <i>どれが一番人気ですか</i> (which is most popular?). Nudge with もう少し. Keep each comparison short and stack them; that’s exactly how prices, sizes, and speeds get weighed out loud.',
'One breath, the whole week: rank two with <b>AよりBのほうが</b>, ask with <b>どちらが</b>, crown the top with <b>一番</b>, and handle ties or shortfalls with <b>と同じ</b> / <b>ほど〜ない</b>. Season with もっと・ずっと・もう少し for intensity. In real chat you rarely finish the full frame — half of it (<i>車のほうが速い</i>) already lands the comparison.'
];
G[9]=[
'Your polite “would you like to…?” Take the ます-form and turn it into a negative question: <b>〜ませんか</b> — <i>一緒に行きませんか</i> (won’t you go with me?). The negative framing leaves the other person easy room to decline, so it sounds warmer and less pushy than a flat suggestion. Ideal for a first invite to someone you don’t know well.',
'Once you both clearly want to, this rallies the group: ます-stem + <b>ましょう</b> — <i>始めましょう</i> (let’s start), <i>そろそろ行きましょう</i> (let’s get going). It assumes agreement, so save it for after the yes rather than the opening pitch. You’ll also hear it as a warm one-person nudge: <i>頑張りましょう</i> (let’s do our best).',
'Add か to ましょう and you’re now <i>checking</i>, not declaring: <b>〜ましょうか</b>. Two flavours — offering to help (<i>荷物を持ちましょうか</i>, shall I carry that?) and floating a shared plan (<i>何を食べましょうか</i>, what shall we eat?). The か hands the choice to them, which makes it the polite way to volunteer without seeming to impose.',
'The friends-only versions. Drop the polite ending: a plain negative with rising tone <b>〜ない？</b> (<i>お茶しない？</i>, wanna grab tea?) mirrors ませんか, and the volitional <b>〜よう</b> (<i>行こう！</i>, let’s go!) mirrors ましょう. Same two jobs — invite and rally — just stripped of ます. Keep these out of messages to your boss; they’re strictly casual.',
'This is the engine behind casual 〜よう and set-ups like 〜ようと思う (I think I’ll…). ru-verbs: drop る, add <b>よう</b> (食べ<b>よう</b>). u-verbs: swap the final -u for -ō (行<b>こう</b>, 飲<b>もう</b>). Memorise the two irregulars — する→<b>しよう</b>, 来る→<b>来よう</b>. Once it’s automatic, <i>週末どうしようか</i> (what shall we do this weekend?) rolls right out.',
'How you answer the invite. Accept warmly with <b>いいですね</b> or <b>ぜひ</b> (love to!). To decline, never bark いいえ — trail off with <b>ちょっと…</b> plus a soft reason: <i>その日はちょっと…</i> (that day’s a little…). The unfinished sentence <i>is</i> the “no,” and everyone reads it that way. Softness matters more here than in almost any other reply.',
'The whole invitation arc in one map: open politely with <b>ませんか</b>, rally once they’re in with <b>ましょう</b>, offer or check with <b>ましょうか</b>, and go casual among friends with <b>〜ない？</b> / <b>〜よう</b>. Then answer well — <b>いいですね</b> to jump in, a trailing <b>ちょっと…</b> to bow out. The politeness lives in how softly you invite and refuse.'
];
G[10]=[
'Your first “can do.” For ru-verbs, drop る and add <b>られる</b>: 食べる→<b>食べられる</b> (can eat), 見る→<b>見られる</b> (can see, can watch). It covers both personal ability and general possibility. One heads-up you’ll meet on Day 4 — the object usually flips to が, so it’s 寿司<b>が</b>食べられる, not を.',
'Same idea for u-verbs, via a clean sound-swap: change the final -u to <b>-eru</b>. 書く→書<b>ける</b> (can write), 飲む→飲<b>める</b> (can drink), 話す→話<b>せる</b>. The result behaves like a ru-verb, so negative and past come easily — 書けない, 書けた. Say <i>ひらがなが読める</i> (I can read hiragana) to feel the shift onto the え-row.',
'Just two to memorise, but you’ll reach for them daily. する→<b>できる</b> — the all-purpose “can do, be able”: <i>運転できる</i> (can drive), <i>予約できます</i> (can book). 来る→<b>来られる</b> (can come): <i>明日来られる？</i> (can you come tomorrow?). Because できる pairs with any noun+する verb, it quietly covers a huge slice of everyday “can.”',
'The particle switch that trips everyone up. When a verb goes potential, its を-object usually turns to <b>が</b>: 日本語<s>を</s>話す → 日本語<b>が</b>話せる (can speak Japanese). Ability describes a state, not an action landing on an object — hence が. You’ll still catch を in fast speech, but が is the clean, expected choice: <i>車が運転できる</i>.',
'A second route to “can,” handy in writing and signage: dictionary verb + <b>ことができる</b> — <i>ここで写真を撮ることができます</i> (you may take photos here). It means the same as the short potential (撮れます) but sounds more formal and explicit, so rules and notices favour it. In casual speech, stick with the shorter form; ことができる can feel stiff.',
'What you’ll actually hear from friends: ru-verb potentials quietly lose their ら. 見<b>られる</b>→見<b>れる</b>, 食べ<b>られる</b>→食べ<b>れる</b> (called ら抜き言葉). It sounds natural and even helps — it splits “can” from passive/honorific られる. But it’s still frowned on in essays, tests, and formal writing, so recognise it everywhere and produce it only when you’re being casual.',
'Map the whole system in one go: ru-verbs drop る and add <b>られる</b>; u-verbs shift -u to <b>-eru</b>; memorise する→<b>できる</b>, 来る→<b>来られる</b>. Whatever the verb, its object leans to <b>が</b> — <i>日本語が話せる</i>. Reach for ことができる when you need to sound formal, and expect the ら to vanish (食べれる) in casual talk. Match the form to the room.'
];
G[11]=[
'Reach for this to list a few example activities without claiming that’s all you did. Take each verb’s た-form and add り, then close with する: <i>週末は掃除したり、買い物したりします</i> (on weekends I clean, shop, and so on). The nuance is “among other things” — a sample, not a full sequence. Two verbs is the usual rhythm; the closing する carries the tense.',
'The formation shortcut: if you can say the plain past, you can build たり. Just add <b>り</b> to the た/だ form — 行った→行っ<b>たり</b>, 飲んだ→飲ん<b>だり</b>, 食べた→食べ<b>たり</b>. The voicing (た vs だ) carries straight over from the past tense, so there’s nothing new to learn. Nail the past form and たり comes for free.',
'For two things at once, done by one person. Attach <b>ながら</b> to the ます-stem of the background action, then state the main one: <i>音楽を聞きながら勉強する</i> (I study while listening to music). The ながら clause is the side activity; the real point sits in the final verb. Perfect for “I do X while Y-ing” — 歩きながら, 食べながら, and so on.',
'Two guardrails keep ながら correct. First, <b>one person</b> must do both actions — you can’t say “I cook while she sings” with ながら. Second, the ながら verb is the <i>background</i>; the sentence’s real focus is the final verb, so <i>テレビを見ながら食べる</i> centres on eating, not watching. Break either rule and you want something else, like 〜ている間に.',
'Both link actions, but they promise different things. <b>て</b> gives a complete, ordered run — <i>起きて、食べて、出かけた</i> (got up, ate, then left, in that order). <b>たり</b> gives a loose sample in no fixed order — <i>食べたり飲んだりした</i> (ate, drank, that kind of thing). Ask yourself: full sequence, or just examples? That one question picks the form for you.',
'When one reason isn’t enough, stack them with <b>し</b>. Attach it to plain forms and pile them up: <i>この店は安いし、近いし、よく行く</i> (it’s cheap, it’s close, so I go a lot). It implies “and there’s more,” which feels warm and persuasive rather than a single blunt から. Often you just leave it trailing — <i>おいしいし…</i> — and the “so” is understood.',
'The week’s four connectors, sorted by job: sample a few activities with <b>〜たり〜たり</b>, do two at once with <b>〜ながら</b>, walk through a full ordered sequence with <b>て</b>, and stack reasons with <b>〜し</b>. The quick test is intent — examples or full list? one actor, or a pile of reasons? Name what you’re doing and the right connector picks itself.'
];
G[12]=[
'Reach for <b>とき</b> whenever you want to anchor one event to another — <i>“when I was a kid,” “when you leave.”</i> Build it by planting <b>とき</b> after a plain clause: 子供の<b>とき</b>, 暇な<b>とき</b>, 食べる<b>とき</b>. Remember it frames a whole situation, not a clock reading — for <i>“at 3:00”</i> you still say 三時に.',
'The verb right before <b>とき</b> sets the clock. <b>Dictionary form</b> means the main action happens <i>before/as</i> it unfolds — 日本へ<b>行くとき</b>、カメラを買った (bought it <i>on the way</i>). <b>Past た</b> means <i>after</i> it is finished — 日本へ<b>行ったとき</b> (bought it <i>once there</i>). Pick the tense by asking: had the first action already finished?',
'Use <b>〜前に</b> for what you do <i>before</i> something else. The cue stays fixed: <b>dictionary form + 前に</b>, even about the past — 寝る<b>前に</b>歯を磨く, and 日本に<b>来る前に</b>ひらがなを勉強した (verb stays 来る, never 来た). For a noun, add の: 食事<b>の前に</b>. That locked dictionary form trips up beginners, so drill it.',
'Flip 前に around: <b>〜あとで</b> is what you do <i>after</i> A is done. The cue is <b>past た + あとで</b> — 昼ご飯を<b>食べたあとで</b>、散歩した; a noun takes の: 仕事<b>のあとで</b>. The た stays put even for future plans. It stresses that A fully finished first, so reach for it when the order genuinely matters.',
'When B should follow <i>right after</i> A — and often depends on it — use <b>〜てから</b>. Just add <b>から</b> to the て-form: 手を洗っ<b>てから</b>ご飯を食べる. Next to あとで, てから feels tighter and more step-by-step: <i>“first do A, then B.”</i> Tip: keep one 〜てから per sentence, or it starts to sound like a chain of chores.',
'These two look alike but split by verb type. <b>まで</b> = keep doing something <i>up until</i> a point (ongoing): 5時<b>まで</b>働く. <b>までに</b> = get a one-shot thing done <i>by</i> a deadline: 5時<b>までに</b>レポートを出す. Quick test: if the verb is continuous (wait, work) use まで; if it is a single moment (finish, submit) use までに.',
'Pull the week together by picturing a timeline. Set the scene with <b>とき</b> (行くとき vs 行ったとき), mark <i>before</i> with dictionary + <b>前に</b>, <i>after</i> with past + <b>あとで</b>, and chain steps with <b>〜てから</b>. Close deadlines with <b>まで</b> (until) vs <b>までに</b> (by). Self-test: 朝ごはんを食べ<b>てから</b>、出かける<b>前に</b>… — can you finish it naturally?'
];
G[13]=[
'This is the textbook <i>“have to.”</i> Build it from the ない-form: drop ない, add <b>なければならない</b> — 行く → 行か<b>なければならない</b> (行かなければなりません for polite). Literally <i>“if you don’t, it won’t do,”</i> so it sounds firm and a little formal — perfect for rules, deadlines and written notices. In everyday chat people trim it right down (see Day 3).',
'The whole family rests on one move: turn any <b>ない</b> into <b>なければ</b> by dropping the final い and adding ければ — 食べ<b>ない</b> → 食べ<b>なければ</b>, 行かない → 行かなければ. Master this and ならない, なくてもいい and casual なきゃ all fall out of it. Bonus: 〜なければ alone is just <i>“if (you) don’t,”</i> a plain conditional.',
'Spoken Japanese almost never says the full form — it contracts. <b>なければ → なきゃ</b> and <b>なくては → なくちゃ</b>, and the tail (ならない/いけない) usually just drops off: もう<b>行かなきゃ</b>！ = <i>“I gotta go!”</i> These feel warm and casual — great for friends, self-talk and texts, but keep them out of formal writing and emails.',
'The relief valve: <b>〜なくてもいい</b> tells someone they <i>don’t have to</i> do it. From the ない-form, swap ない for <b>なくてもいい</b> — 来る → 来<b>なくてもいい</b>, 払う → 払わ<b>なくてもいい</b>. Add ですよ to reassure: 急がなくてもいいですよ (<i>“no need to rush”</i>). It is the exact counterweight to なければならない — permission, not pressure.',
'Two ways to nudge someone. <b>〜た方がいい</b> gives concrete advice — note it takes <b>past た</b>: 早く寝<b>た方がいい</b> (<i>“you’d better sleep early”</i>). <b>〜べき</b> (dictionary + べき) is more <i>“should on principle,”</i> a touch formal: 約束は守る<b>べき</b>だ. Careful — 方がいい can sound urgent, so add ね when you are only suggesting, not scolding.',
'This is your register day — same idea, different clothes. At work or on signs, go full: 提出し<b>なければなりません</b>. With friends, contract it: 出さ<b>なきゃ</b>. Reassure a worrier with <b>なくてもいい</b>: 予約しなくてもいいですよ. And advise gently with <b>方がいい</b>: 早めに行った方がいいよ. Reading the room — who, where, how formal — matters as much as the grammar.',
'Sort the week into four moods. <b>Must</b>: なければならない (formal) / <b>なきゃ・なくちゃ</b> (casual). <b>Need not</b>: なくてもいい. <b>Had better / should</b>: た方がいい・べき. All but 方がいい grow from one root — turn ない into <b>なければ</b>. Self-test: can you say <i>“I have to work today, but I don’t have to come tomorrow”</i> in one breath?'
];
G[14]=[
'When you are unsure which <i>“if”</i> to use, <b>〜たら</b> is the safe default — it covers hypotheticals, one-off futures and <i>“once X happens.”</i> Formation is easy: make the plain <b>past</b>, then add ら — 食べた → 食べ<b>たら</b>, 安い → 安かっ<b>たら</b>, 雨 → 雨だっ<b>たら</b>. お金があっ<b>たら</b>、旅行する = <i>“if I have money, I’ll travel.”</i>',
'Beyond <i>“if,”</i> たら also narrates a <b>discovery</b>: <i>“when I did A, I found B.”</i> Same 〜たら, but B lands in the <b>past</b> and is usually surprising or out of your control — 家に帰っ<b>たら</b>、誰もいなかった (<i>“when I got home, nobody was there”</i>). No hypothetical here; A really happened. Spot this whenever たら is followed by a past-tense result.',
'Reach for <b>〜ば</b> for general truths and cause-and-effect — the <i>“if this, then naturally that”</i> of proverbs and rules. Change the final <b>-u to -e</b> and add ば: 行く → 行<b>けば</b>; い-adjectives go 安い → 安<b>ければ</b>. It shines in set phrases: 〜ばいい (<i>“you just have to…”</i>) and 〜ばよかった (<i>“I wish I had…”</i>). 練習すれば、上手になる.',
'Use <b>〜と</b> for results that are <i>automatic</i> — natural laws, machines, directions, habits. Just add <b>と</b> to the dictionary form: 春になる<b>と</b>、桜が咲く; このボタンを押す<b>と</b>、切符が出る. The catch: because B is inevitable, it <b>can’t</b> be a request, command or invitation. Ideal for directions — まっすぐ行く<b>と</b>、左にあります (<i>“go straight and it’s on the left”</i>).',
'Pick <b>〜なら</b> to respond to something just mentioned — <i>“if that’s what you mean / if that’s the case.”</i> Attach <b>なら</b> to a noun or plain form: 温泉<b>なら</b>、箱根がいい (<i>“if it’s hot springs you want, Hakone”</i>). It uniquely comments on the other person’s topic, and its B can even come <i>before</i> A in time: 行く<b>なら</b>、これを着て (<i>“if you’re going, wear this”</i>).',
'A quick chooser when all four tempt you. Responding to someone’s topic? <b>なら</b>. Automatic, always-true result? <b>と</b>. General principle or a wish? <b>ば</b>. Anything else — one-time futures, <i>“once X happens”</i>? <b>たら</b>, the safe all-rounder. Rule of thumb: と and ば can’t take a command in B, but たら and なら can — おいしかっ<b>たら</b>、買って！',
'Line the four up by their signature move. <b>たら</b> = plain past + ら, the flexible default. <b>ば</b> = -u→-e + ば, general truths and wishes. <b>と</b> = dictionary + と, automatic results (no command in B). <b>なら</b> = picks up the other person’s topic. Self-test: render <i>“if it rains, I won’t go”</i> — 雨が降っ<b>たら</b>、行かない — then try each of the others and feel which fits.'
];
G[15]=[
'Use <b>あげる</b> when something moves <i>away</i> from your side — you (or your group) give to someone else. Frame it giver<b>は</b> receiver<b>に</b> thing<b>を</b>あげる: 私は妹にお菓子を<b>あげた</b>. Never use it for gifts coming <i>to</i> you — that job is くれる. Register: 差し上げる is humble (to a superior), and やる is for pets and plants.',
'When a gift comes <i>toward</i> you or your family, switch to <b>くれる</b>. The giver takes が, and the receiver is always <i>you or your side</i> — often left unsaid: 田中さんが(私に)手袋を<b>くれた</b>. You can’t make yourself the subject of くれる. It carries a warm <i>“they did me the kindness”</i> nuance; the honorific くださる respects a higher-status giver.',
'Flip the camera onto the <b>receiver</b> with <b>もらう</b> — <i>you got</i> something from someone. Frame it receiver<b>は</b> source<b>に</b>(or から) thing<b>を</b>もらう: 私は先輩に辞書を<b>もらった</b>. Both に and から mark where it came from. When the giver outranks you, swap in the humble <b>いただく</b> to show respect: 先生にアドバイスを<b>いただいた</b>.',
'Attach <b>あげる</b> to a て-form to give an <i>action</i>, not a thing — a favor headed <i>outward</i>: 妹に本を読ん<b>であげた</b> (<i>“read it for her”</i>). Handle with care: 〜てあげる can sound like you are advertising your own kindness, so it feels pushy toward superiors. With a boss, drop the あげる or rephrase — even humble 〜て差し上げる can come off as presumptuous.',
'Gratitude built into grammar: <b>〜てくれる</b> = someone did an action <i>for me</i>. Add <b>くれる</b> to the て-form: 友達が宿題を手伝っ<b>てくれた</b> (<i>“helped me out”</i>). It signals appreciation on its own and pairs naturally with thanks — 来<b>てくれて</b>ありがとう. For a higher-status helper, lift it to くださる: 先生が教え<b>てくださった</b>.',
'Use <b>〜てもらう</b> when you <i>get</i> someone to do something for you — often because you asked. Frame it you<b>は</b> doer<b>に</b> action-て<b>もらう</b>: 友達に引っ越しを手伝っ<b>てもらった</b>. Subtle contrast: 〜てくれる spotlights their kindness (they started it); 〜てもらう spotlights you receiving it (often arranged). Bump up to the humble <b>いただく</b> for superiors: 先生に見<b>ていただいた</b>.',
'The whole week is a compass. Outward from you: <b>あげる</b> / <b>〜てあげる</b>. Inward to you or your <i>uchi</i> (in-group): <b>くれる</b> / <b>〜てくれる</b>. The receiver’s view: <b>もらう</b> / <b>〜てもらう</b>. Then layer politeness — humble 差し上げる・いただく for your own side, honorific くださる for a respected giver. Self-test: 田中さんが手伝っ<b>てくれた</b> or <b>てあげた</b> — which way does the arrow point?'
];
G[16]=[
'Voice an opinion or guess with <b>〜と思う</b>. Put a <b>plain-form</b> clause in front of <b>と思う</b>: 明日は雨だ<b>と思う</b> (<i>“I think it’ll rain”</i>). Use it to soften claims into personal views rather than facts. Note the split: 〜と思う is <i>my</i> opinion right now, while 〜と思っている describes a lasting belief — or someone else’s: 彼は行こう<b>と思っている</b>.',
'The golden rule of quoting: whatever sits before <b>と</b> is <b>plain form</b>, no matter how polite the whole sentence is. Say 行く<b>と思います</b>, never 行きますと思います — politeness lives only on the <i>final</i> verb. The と-clause is a quotation, so it stays casual inside: 学生だ<b>と言いました</b>. Fixing this one habit clears up most beginner quoting slips.',
'Report speech with <b>〜と言う</b>, two ways. <b>Direct</b> keeps the exact words in 「…」: 彼は「行きます」<b>と言った</b> — politeness and all preserved. <b>Indirect</b> paraphrases with a plain clause: 彼は行く<b>と言った</b>. Direct feels vivid and verbatim; indirect is smoother for retelling. In casual speech と言う shrinks to <b>って</b>: 行くって (<i>“he says he’s going”</i>).',
'To pass on what someone told you, use <b>〜と言っていた</b> — the <i>was-saying</i> form, not plain 言った. Build it plain clause + <b>と言っていた</b>: 田中さんが今日は休む<b>と言っていた</b> (<i>“Tanaka said he’s off today”</i>). The 〜ていた framing marks it as news you <b>heard earlier</b> from a known person, which is why it beats 言った for relaying messages.',
'Two dials for uncertainty. <b>かもしれない</b> = <i>“might, maybe”</i> — a real possibility, roughly even odds or less: 遅れる<b>かもしれない</b>. <b>でしょう</b> = <i>“probably,”</i> higher confidence and the voice of weather forecasts: 明日は晴れる<b>でしょう</b>. Both take a plain form in front (drop だ before でしょう). Casual shortcuts: <b>かも</b> and <b>だろう</b> — 雨かも, 無理だろう.',
'Relay hearsay with <b>〜そうだ</b> — <i>“I hear that…, apparently.”</i> It attaches to a <b>full plain form</b>: 田中さんは来ない<b>そうだ</b>; 天気予報によると、台風が来る<b>そうだ</b>. Crucial: don’t confuse it with the <i>looks-like</i> そう, which grabs the verb <b>stem</b> (降り<b>そう</b> = <i>“looks about to rain”</i>). Full clause before そう = hearsay; bare stem = appearance.',
'Tie the week together around <b>と</b> and the <i>plain-form-before-と</i> rule. Think it: <b>と思う</b>. Say it: <b>と言う</b> (direct 「…」 vs indirect). Relay it: <b>と言っていた</b> and hearsay <b>そうだ</b>. Hedge it: <b>かもしれない</b> (might) vs <b>でしょう</b> (probably). Self-test: turn <i>“the teacher said the test is tomorrow”</i> into 先生が試験は明日だ<b>と言っていた</b> — plain form locked inside と.'
];
G[17]=[
'Reach for these whenever you describe an action, and pick the twin by <i>who or what</i> causes it. Someone does it → transitive with を (<b>ドアを開ける</b>, I open the door); it happens on its own → intransitive with が (<b>ドアが開く</b>, the door opens). If you can name the doer, use the を twin.',
'Reach for this to say something was <b>deliberately set up and left that way</b>, often as preparation. Build it from a transitive verb’s て-form + ある: <b>窓が開けてある</b> — the window has been opened on purpose. The object takes が, not を. It quietly implies a person did it for a reason, so it’s perfect for “it’s already been taken care of.”',
'Use this to report a state you simply <i>see</i>, with no thought of who caused it. Build it from the <b>intransitive</b> twin’s て-form + いる: <b>窓が開いている</b> — the window is open. Where てある hints at a doer, ている stays neutral, like a plain caption of the scene in front of you.',
'When both could fit the same scene, let <b>intent</b> decide. てある (transitive verb) says someone did it on purpose; ている (intransitive verb) just reports how things are. <b>電気がつけてある</b> — left on deliberately — versus <b>電気がついている</b> — it’s simply on. If you want to hint that someone arranged it, reach for てある.',
'Drill these six until the right twin comes out on reflex: 閉める/閉まる, 入れる/入る, 出す/出る, 消す/消える, 開ける/開く, つける/つく. The first of each pair is the “I do it” verb (takes を); the second is “it happens on its own” (takes が). Don’t trust the endings to sort them — learn each pair as one unit and say it with both particles.',
'The instant you add a particle, let the <b>verb</b>, not the meaning, choose it. Transitive twin → を (<b>ドアを閉める</b>, I close the door); intransitive twin → が (<b>ドアが閉まる</b>, the door closes). Quick check: swap in the other twin and watch the particle flip with it. Build that reflex and the pairs run themselves.',
'Pull the week together by narrating a real room out loud: what is <b>open</b> (窓が開いている), what is <b>on</b> (電気がついている), and what was deliberately <b>set up</b> (〜てある). Whenever a を or が wobbles, name the verb first — transitive takes を, intransitive takes が — and let it choose for you.'
];
G[18]=[
'Use this whenever you need a form fast. Run each verb straight across all five: て (linking), た (past), ない (negative), potential (can), volitional (let’s) — <b>飲む → 飲んで・飲んだ・飲まない・飲める・飲もう</b>. Lock the verb’s group first (ru / u / irregular) and every form falls out of it. This is a speed drill, not new grammar.',
'Reach here whenever you say <i>if</i> or <i>when</i>. たら is the safe all-rounder (<b>時間があったら行きます</b>); ば states a general condition (<b>安ければ買います</b>); と gives an automatic result (<b>押すと開きます</b>, press and it opens); なら responds to a topic just raised (<b>行くなら朝がいい</b>). When in doubt, たら almost always fits.',
'Use these to track <b>who gives to whom</b>. Aim the verb by direction: あげる (I give outward), くれる (someone gives to <i>me</i>), もらう (I receive, source marked with に or から). <b>友達が私に本をくれた</b> — a friend gave me a book. The classic trap: a gift heading toward you is くれる, never あげる.',
'Reach here to report a thought, a quote, a guess, or hearsay. Each clips onto the <b>plain form</b>: <b>行くと思う</b> (I think I’ll go), <b>行くと言った</b> (said he’d go), <b>行くかもしれない</b> (might go), <b>行くそうだ</b> (I hear he’ll go). Key habit — keep the verb plain, not polite: 行きますと思う is wrong.',
'Grab the right one by its <b>day job</b>: は marks the topic, が the subject or new info, を the object, に a destination or time (<b>7時に</b>), で the place of an action or the means (<b>バスで</b>), から/まで from and until. Handy split: “where something happens” is で, “where you’re heading” is に.',
'This is pure output — turn English into Japanese on the spot. Build outside-in: set the topic with は, park the verb at the very end, then slot the objects and particles between. Say the whole thing aloud before you check. Don’t hunt for a word-for-word match; aim for what a native speaker would naturally say.',
'Use this to decide what to re-drill before moving on. Score yourself topic by topic — verb forms, conditionals, giving and receiving, quoting, particles — then pour your time into only the weakest. The honest test: make up a fresh sentence for each on the spot. Whatever you can’t produce cold is exactly what to review.'
];
G[19]=[
'Pull this out when you meet someone and want more than your name. Frame it: はじめまして → <b>…は</b> + your name → a detail or two (job, hometown, a like) → よろしくお願いします. One が好き makes you sound human: <b>コーヒーが好きです</b>. Aim for about 20 seconds — real enough to land, short enough to hold together.',
'Use this to walk through your day. Sequence it with time words and the て-form: <b>7時に起きて、それから…</b>. Set the frequency near the verb — いつも, よく, ときどき. Watch the pair rule: あまり and ぜんぜん need a <b>negative</b> verb (<b>あまり見ません</b>, I don’t watch much). Clock times take に; linked actions ride the て-form.',
'Reach here to give a view, not just a fact. Shape it as <b>reason + claim</b>: put the から reason first, land the opinion last — <b>安いから、いいと思います</b> (it’s cheap, so I think it’s good). Wrapping the claim in と思う softens it to “I think,” rather than a flat pronouncement. A plain が好き works as the claim too.',
'Use this to invite someone and settle a plan. Open soft, then close once you both agree: <b>行きませんか</b> (won’t you go?) → <b>行きましょう</b> (let’s go). ましょうか offers a step — “shall we? shall I?” Start with ませんか rather than ましょう: it’s the politer opener, because it leaves the other person room to decline.',
'Pull these out the moment a conversation gets away from you. Keep a rescue kit ready: <b>もう一度お願いします</b> (once more, please), <b>ゆっくりお願いします</b> (slowly, please), <b>どういう意味ですか</b> (what does it mean?). Open with すみません to soften the ask. Using these beats freezing — they buy time and keep the talk alive.',
'Use this to tell what you did — yesterday, your weekend, a trip. Chain the middle actions with て-forms and mark tense only at the <b>end</b>: <b>起きて、食べて、出かけました</b>. That one past ending covers the whole chain, so you don’t tense every verb. Drop in 〜てから for “after that” when you want a clearer beat between events.',
'Take stock at the finish line: name three things you can now do <b>cold</b> — introduce yourself, describe a routine, give an opinion, make a plan, tell a past story — plus one to revisit. Be strict about “can-do”: it means out loud, with no notes. If you still need to peek, it isn’t locked in yet.'
];
G[101]=[
'This is your very first sentence — use it to say what someone or something <b>is</b>. The frame never changes: <b>X は Y です</b>, X is Y. は marks the topic (say it “wa”), and です is a polite “am / is / are.” <b>わたしは学生です</b> — I am a student. Nail this and the rest of the week just adds pieces to it.',
'Use this to turn any です sentence into a yes or no question — just add <b>か</b> to the end. Nothing else moves: <b>学生ですか</b> — are you a student? Answer with はい (yes) or いいえ (no). か does the job an English question mark does, so you don’t need to raise your voice; let か do the asking.',
'Use this to say something is <b>not</b> so. Keep the frame and swap です for <b>じゃありません</b>: <b>学生じゃありません</b> — I am not a student. Register note: じゃありません is the normal polite negative for daily talk, while ではありません (say “dewa”) sounds a touch more formal — save it for writing or careful speech.',
'Use this to talk about the past — what something <b>was</b>. Turn です into <b>でした</b>: <b>去年、学生でした</b> — last year I was a student. For “was not,” stretch it to じゃありませんでした. The four corners: です (is) · じゃありません (is not) · でした (was) · じゃありませんでした (was not). Only the ending moves; X は stays put.',
'Use this for “me too” and “that one as well.” Simply replace は with <b>も</b> — never use both together: <b>わたしも学生です</b> — I am a student too. That one swap is the whole move: は introduces a fresh topic, while も says “same as the last one.” <b>田中さんも学生です</b> — Tanaka is a student too.',
'Use の to glue two nouns into one idea — owner, type, or origin. Owner first, then <b>の</b>, then the thing: <b>わたしの本</b> — my book; <b>日本語の先生</b> — a Japanese teacher. Think of it as “’s” or “of.” Order is everything: in A の B, B is the main thing and A tells you whose or what kind.',
'Bring the week together in one small exchange: state a fact (X は Y です), ask about one (〜ですか), and correct a wrong guess (〜じゃありません). For example — <b>学生ですか。いいえ、学生じゃありません。先生です。</b> Being able to say, ask, and fix a fact politely really is the core of beginner Japanese. You’re there.'
];
G[102]=[
'Use these to name a thing you’re pointing at, and let <b>distance</b> choose the word: <b>これ</b> (near me), <b>それ</b> (near you), <b>あれ</b> (far from us both). They work like a noun on their own: <b>これは本です</b> — this is a book. Each already means “this one,” so don’t add a noun straight after it.',
'Use this set when you want to point <b>and</b> name the thing at once. Each one must be followed by a noun: <b>この本</b> (this book), <b>その本</b> (that book), <b>あの本</b> (that book over there). The clean split: これ stands alone, この always needs a noun after it. Distances are the same — near me, near you, far from both.',
'Use these to point at a <b>place</b> rather than a thing — same こ・そ・あ logic: <b>ここ</b> (here, by me), <b>そこ</b> (there, by you), <b>あそこ</b> (over there, away from us). They act like nouns: <b>トイレはあそこです</b> — the toilet is over there. This little trio rescues you the moment you need to ask for or give directions.',
'Use the ど-words to ask which, where, or what: <b>どれ</b> (which one, from three or more), <b>どの＋noun</b> (which book), <b>どこ</b> (where), <b>何</b> (what, “nan / nani”). Finish with か: <b>トイレはどこですか</b> — where is the toilet? They mirror the sets you know — どれ stands alone, どの needs a noun, just like これ and この.',
'Reach for this polite set for directions, shops, and introductions — it means “this way / this one / this person”: <b>こちら</b>, <b>そちら</b>, <b>あちら</b>, and the question <b>どちら</b>. It gently introduces people: <b>こちらは田中さんです</b> — this is Mr Tanaka. It is the softer, more formal cousin of これ and ここ, so it suits customers and strangers.',
'Use this tiny kit to actually shop. Point and ask the price: <b>これはいくらですか</b> — how much is this? To buy, use を + ください: <b>これをください</b> — I’ll take this one. Adding another? Swap を for も: <b>これもください</b> — this one too, please. Three short lines and you can get through a store on your own.',
'Tie it all together by running the grid live: こ (near me), そ (near you), あ (far from both), ど (the question). Point at something near (<b>これ</b>), point far (<b>あれ</b>), then ask which one (<b>どれですか</b>). Once the こ・そ・あ・ど shape feels automatic, every new member — この, ここ, こちら — simply slots into it.'
];
G[103]=[
'Reach for <b>は</b> when you want to name what the sentence is <i>about</i>, then comment on it. Build it as <b>topic + は + comment</b>: 私<b>は</b>アメリカ人です <i>(As for me, American)</i>. Remember it is written は but said <i>wa</i>, and it works like a gentle “as for…” — the everyday, all-purpose starter.',
'Grab <b>も</b> to pile on a second thing that fits the same comment — the “…too” feeling. It <i>replaces</i> は or が, never sits beside them: 私は日本人です → 私<b>も</b>日本人です <i>(I am Japanese too)</i>. A quick 私も！ <i>(Me too!)</i> is one of the friendliest things you can say.',
'Use <b>が</b> to shine a spotlight on <i>new</i> or unknown information — especially to answer “who?” or “what?”. Build it as <b>subject + が</b>: 誰<b>が</b>来ましたか <i>(Who came?)</i> → 田中さん<b>が</b>来ました <i>(Tanaka did)</i>. The weight falls on the word before が, so it names the one that matters.',
'When you are unsure which to pick, ask: is this <i>old, shared</i> info or <i>new</i> info? Known background takes <b>は</b>; the fresh, asked-about part takes <b>が</b>. 猫<b>が</b>います <i>(There is a cat — new)</i>, then 猫<b>は</b>かわいいです <i>(The cat is cute — now known)</i>. Handy rule: <b>new before が, known before は</b>.',
'A small set of words — 好き <i>(like)</i>, 上手 <i>(good at)</i>, ある/いる <i>(exist)</i> — put <b>が</b> on the thing, not を. Build it as <b>thing + が + 好き</b>: 寿司<b>が</b>好きです <i>(I like sushi)</i>. It literally means “sushi is likeable”, so let が, not を, mark what you love or are skilled at.',
'Beyond topics, <b>は</b> can draw a quiet contrast — “this one, at least”. Mark the singled-out item with は and let the “but…” stay unspoken: コーヒー<b>は</b>飲みます <i>(I do drink coffee — tea, maybe not)</i>. It is a gentle way to hedge, so it often softens a partial “no” without sounding blunt.',
'Put the three together with one quick check: naming the topic? <b>は</b>. Adding “…too”? <b>も</b>. Spotlighting new info or answering “who?” <b>が</b>. Try one sentence each — 私<b>は</b>学生です・私<b>も</b>です・誰<b>が</b>来ますか — and you have the week. These three do the heavy lifting in almost every sentence, so this practice pays off fast.'
];
G[104]=[
'Reach for <b>います</b> to say a living, moving thing is there — people, animals, even fish and bugs. Build it as <b>thing + が + います</b>: 犬<b>が</b>います <i>(There is a dog)</i>. The test is “can it move itself?” — if yes, it takes います. For a person you know: 田中さんがいます <i>(Tanaka is here)</i>.',
'Use <b>あります</b> for things that do <i>not</i> move on their own — objects, plants, places, even plans on your calendar. Build it the same way: <b>thing + が + あります</b>: 車<b>が</b>あります <i>(There is a car)</i>. A tree stays put, so 木があります. If it cannot walk off by itself, あります is your verb.',
'To say <i>where</i> something is, add <b>に</b> after the place: <b>place + に + thing + が + あります/います</b>. 部屋<b>に</b>猫がいます <i>(There is a cat in the room)</i>. The に quietly pins the location down, and Japanese usually names the place first, then the thing found there — the reverse of English word order.',
'Pick the particle by what is <i>known</i>. Reporting what exists (new)? Use <b>が</b>: 机の上に本<b>が</b>あります. Locating something already known? Make it the <b>は</b> topic: 本<b>は</b>どこにありますか <i>(Where is the book?)</i>. Short version: <b>が</b> answers “what is there?”, <b>は</b> answers “where is it?”.',
'For precise positions, sandwich a position word with <b>の … に</b>: <b>noun + の + 上/下/中/となり + に</b>. 机<b>の上に</b> <i>(on the desk)</i>, 箱<b>の中に</b> <i>(inside the box)</i>, 駅<b>のとなりに</b> <i>(next to the station)</i>. Do not forget the little の linking them — テーブルの上, never テーブル上. Then finish with あります or います.',
'To say how many, drop the count right before the verb — no extra particle: <b>thing + が + [number] + あります</b>. りんご<b>が二つ</b>あります <i>(There are two apples)</i>. For everyday objects the 一つ・二つ・三つ set is your safe default. Notice the number hugs the verb: …が三つあります, not …三つが.',
'One question settles most of this week: can it move on its own? Living and moving → <b>います</b>; everything else → <b>あります</b>. Frame it as <b>place + に + thing + が + (verb)</b>: 公園に子供<b>が</b>います・かばんの中に本<b>が</b>あります. Add a position word or a count when you need detail, and existence is fully in your toolkit.'
];
G[105]=[
'The <b>ます</b>-form is your polite, do-anywhere verb — and it covers both <i>now</i> and <i>later</i> at once. 毎日食べます <i>(I eat every day)</i> or 明日食べます <i>(I will eat tomorrow)</i> use the same 食べます; context supplies the time. It is the safe, respectful choice with anyone, so lean on it freely as a beginner.',
'To say you do <i>not</i> or will not do something, just switch <b>ます → ません</b>. 飲みます → 飲み<b>ません</b> <i>(do not drink)</i>. Nothing else changes, and it stays polite and present or future. お酒は飲みません <i>(I do not drink alcohol)</i> — pair it with contrastive は to decline something smoothly and politely.',
'For things you already did, turn <b>ます → ました</b>. 見ます → 見<b>ました</b> <i>(saw / watched)</i>. It is the polite past, perfect for answering 何をしましたか <i>(what did you do?)</i>: 映画を見ました <i>(I watched a movie)</i>. Just reshape the ending — the verb stem stays exactly the same, so this is an easy swap.',
'To say you did <i>not</i> do something, use <b>ませんでした</b> — literally ません <i>(not)</i> + でした <i>(past)</i>. 行きます → 行き<b>ませんでした</b> <i>(did not go)</i>. It is the longest of the four ます-endings but perfectly regular: 昨日は勉強しませんでした <i>(I did not study yesterday)</i>. Say it slowly at first and it soon rolls off.',
'When a verb acts on something, tag that something with <b>を</b>: <b>object + を + verb</b>. パン<b>を</b>食べます <i>(eat bread)</i>, 水<b>を</b>飲みます <i>(drink water)</i>. It is written を but pronounced <i>o</i>, and it always points to whatever receives the action. Find the “what?” of your verb, and を goes right on it.',
'Two location ideas, two particles. Heading somewhere? Use <b>に</b> or <b>へ</b>: 学校<b>へ</b>行きます <i>(go to school)</i>. Doing an activity somewhere? Use <b>で</b>: カフェ<b>で</b>働きます <i>(work at a cafe)</i>. The trick: に/へ points to a <i>destination</i>, で marks where the <i>action</i> happens. Move with に/へ, act with で.',
'Tie the week together: pick the ending for time and polarity — 〜ます・〜ません・〜ました・〜ませんでした — then feed the verb its particles. 昨日、図書館<b>で</b>本<b>を</b>読みました <i>(Yesterday I read a book at the library)</i> uses で for place, を for object, ました for past. Choose the ending, add を and に/へ/で, and full polite sentences are yours.'
];
G[106]=[
'A quick warm-up grid: 〜ます <i>(do)</i>, 〜ません <i>(do not)</i>, 〜ました <i>(did)</i>, 〜ませんでした <i>(did not)</i>. Same stem every time — only the tail changes for <i>time</i> and <i>yes/no</i>. Run one verb through all four out loud: 行きます・行きません・行きました・行きませんでした. Once that pattern feels automatic, this week is mostly about the particles around it.',
'For a destination, both <b>に</b> and <b>へ</b> work — pick either: 日本<b>に</b>行きます or 日本<b>へ</b>行きます <i>(go to Japan)</i>. へ is pronounced <i>e</i> here and leans a touch more toward “toward”; に is a little more common and also does the arriving-at jobs. As a beginner, choosing either is completely fine.',
'When something is <i>done</i> at a place, mark that place with <b>で</b>: <b>place + で + action</b>. 家<b>で</b>働きます <i>(work at home)</i>, 海<b>で</b>泳ぎます <i>(swim in the sea)</i>. Keep it apart from に: に is a destination you move to, で is the stage where the action plays out. Activity → で.',
'To do something <i>together</i> with someone, use <b>と</b>: <b>person + と + verb</b>. 友達<b>と</b>映画を見ます <i>(watch a movie with a friend)</i>. The same と also links nouns as “and” (パン<b>と</b>卵 = bread and eggs), so let context tell them apart. Add 一緒に for warmth: 友達と一緒に行きます <i>(go together with a friend)</i>.',
'Mark a span with <b>から</b> <i>(from)</i> and <b>まで</b> <i>(to / until)</i> — for either time or place. 9時<b>から</b>5時<b>まで</b>働きます <i>(work from 9 to 5)</i>; 東京<b>から</b>大阪<b>まで</b> <i>(from Tokyo to Osaka)</i>. Use them as a pair or on their own — 3時まで <i>(until 3)</i> is fine solo. Start point から, end point まで.',
'To pin an action to a <i>specific</i> clock time or date, add <b>に</b>: 7時<b>に</b>起きます <i>(get up at 7)</i>, 月曜日<b>に</b>会います <i>(meet on Monday)</i>. Careful — relative words like 今日 <i>(today)</i>, 明日 <i>(tomorrow)</i> and 毎日 <i>(every day)</i> take <i>no</i> に. Rule of thumb: if you could point to it on a clock or calendar, use に.',
'Bring the particles together in one sentence: 月曜日<b>に</b>友達<b>と</b>カフェ<b>で</b>会います <i>(On Monday, I meet a friend at a cafe)</i>, then 9時<b>から</b>11時<b>まで</b>話します <i>(and talk from 9 to 11)</i>. Each little word does one job — <b>に</b> when, <b>と</b> who with, <b>で</b> where, <b>から/まで</b> the span. Name the job, pick the particle, and long sentences click into place.'
];
G[107]=[
'い-adjectives describe in two places. Right <i>before</i> a noun: 高い山 <i>(a tall mountain)</i>. Or at the sentence <i>end</i> with です: この山は<b>高いです</b> <i>(This mountain is tall)</i>. Either way the word keeps its final <b>い</b> — です only adds politeness, so never chop the い off before it. 新しい車, 車は新しいです.',
'To say something is <i>not</i> that quality, swap the final <b>い → くない</b>: 高い → 高<b>くない</b> <i>(not tall)</i>. Add です to stay polite: この店は高くない<b>です</b> <i>(This shop is not expensive)</i>. Only the い changes; the stem never moves. あつい → あつくない, おいしい → おいしくない — the pattern is wonderfully regular.',
'い-adjectives carry their <i>own</i> past tense. Was (positive): い → <b>かった</b> — 楽しい → 楽し<b>かった</b> <i>(was fun)</i>. Was not: → <b>くなかった</b> — 楽しくなかった. Add です to be polite: 楽しかったです. Important: because the adjective already shows past, do <i>not</i> tack でした onto it — 高いでした is a classic slip to avoid.',
'いい <i>(good)</i> is the one rebel. Plain present stays <b>いい</b>: いいです <i>(it is good)</i>. But every other form switches to the <b>よ</b> stem: <b>よくない</b> <i>(not good)</i>, <b>よかった</b> <i>(was good)</i>, <b>よくなかった</b> <i>(was not good)</i>. Never say いくない or いかった. Bonus: よかった！ on its own means “Oh good!” — a hugely useful little reaction.',
'To describe <i>how</i> an action is done, turn the adjective into an adverb: <b>い → く</b>. 早い → <b>早く</b>起きます <i>(get up early)</i>, 大きい → <b>大きく</b>書きます <i>(write big)</i>. It is the same little change as the negative stem, just used with a verb. From よ-friend いい comes よく — よく食べます <i>(eat well / often)</i>.',
'To stack two descriptions, connect the first with <b>くて</b>: い → <b>くて</b>. 安い + おいしい → 安<b>くて</b>おいしい <i>(cheap and tasty)</i>. It is the adjective version of “and”, linking smoothly to whatever follows: この部屋は広くて明るいです <i>(This room is spacious and bright)</i>. Chain a couple and your descriptions instantly sound fuller. (いい → よくて.)',
'The whole い-adjective family in one look: 高い・高くない・高かった・高くなかった, adverb 高く, connector 高くて. Keep the golden rules close — the adjective holds its own past (no でした), and いい always shifts to よ. Try describing your day: 今日は忙しくて大変でした <i>(Today was busy and tough)</i>. Master this family and な-adjectives next week will feel easy.'
];
G[108]=[
'な-adjectives need <b>な</b> only when they sit right before a noun: 静か<b>な</b>部屋 <i>(a quiet room)</i>, 元気<b>な</b>子供 <i>(an energetic child)</i>. End a sentence and the な disappears — just add です: この部屋は<b>静かです</b> <i>(This room is quiet)</i>. So: な to hug a noun, plain + です to finish. きれいな花, 花はきれいです.',
'For “not”, な-adjectives act just like nouns: drop です and add <b>じゃありません</b>. この店は<b>静かじゃありません</b> <i>(This shop is not quiet)</i>. No な, no くない — that い-adjective change never applies here. じゃありません is the everyday polite form; ではありません is its slightly firmer, more written cousin. Casually, じゃない does the same job.',
'Here な-adjectives happily take <b>でした</b> — the very thing い-adjectives refuse. Was: 元気<b>でした</b> <i>(was well)</i>. Was not: 元気<b>じゃありませんでした</b> <i>(was not well)</i>. They follow the same path as nouns with です. So 便利でした <i>(was convenient)</i> is correct, while an い-adjective would never say 高いでした — a handy contrast to keep straight.',
'Where い-adjectives took く, な-adjectives take <b>に</b> to become adverbs: <b>adjective + に + verb</b>. 静か<b>に</b>話します <i>(speak quietly)</i>, きれい<b>に</b>書きます <i>(write neatly)</i>, 元気<b>に</b>あいさつします <i>(greet cheerfully)</i>. Same idea as last week, just に instead of く. Picture it as the twin of 早く — this week it is 静かに.',
'To join descriptions when the first is a な-adjective, connect it with <b>で</b>: この町は<b>静かで</b>きれいです <i>(This town is quiet and pretty)</i>. It is the な-side counterpart of the くて you met last week. You can bridge into an い-adjective too: 元気<b>で</b>優しい人 <i>(a cheerful, kind person)</i>. Think: い-word → くて, な-word → で.',
'Sort the family first, then conjugate. Does it attach straight to a noun keeping い (新し<b>い</b>本)? That is an い-adjective. Does it need な (有名<b>な</b>店)? な-adjective. Beware two impostors — <b>きれい</b> and <b>嫌い</b> end in い but are <i>な</i>-adjectives (きれいな, きれいでした). When unsure, test でした: if it fits, it is a な-word.',
'Two families, side by side: negative い-word 高<b>くない</b> vs な-word 静か<b>じゃありません</b>; past 高<b>かった</b> vs 静か<b>でした</b>; adverb 高<b>く</b> vs 静か<b>に</b>; connect 高<b>くて</b> vs 静か<b>で</b>. Spot the type, then follow its lane. Describe something around you: この部屋は静かで広いです <i>(This room is quiet and spacious)</i>. With both families in hand, you can describe almost anything.'
];
})();
